Homepage
Microfonia/website pull request #4
Opened 2017-07-10 11:48 UTC by davibortolotti

creates the homepage for the website, with a menu button. All responsive to window-scaling and mobile devices.

2017-07-10 15:27 UTC, rafaels88 requested changes

2017-07-10 15:27 UTC, rafaels88 commented on microfonia/templates/base.html
> +	{% block css %} CSS ESPECIFICO AQUI {% endblock %}
Acho que a gente pode tirar esse "CSS ESPECIFICO AQUI" dai haha

2017-07-10 15:27 UTC, rafaels88 commented on microfonia/templates/base.html
> +		<button class="menu-button button-font"><i id=	'menu-open' class="fa fa-bars" aria-hidden="true"></i><i id='menu-close' class="fa fa-times hide" aria-hidden="true"></i>MENU</button>
Deu uma zuada no espaco aqui: "id=	'menu-open'"

2017-07-10 15:27 UTC, rafaels88 commented on microfonia/templates/base.html
> +			TESTE
Aqui tbm 💃

2017-07-10 15:27 UTC, rafaels88 commented on microfonia/templates/base.html
> +	$(".menu-button").toggleClass("button-menu-open");
Da uma identada nesse codigo aqui :p

2017-07-10 15:36 UTC, davibortolotti commented on microfonia/templates/base.html
> +	{% block css %} CSS ESPECIFICO AQUI {% endblock %}
hahahaha ok!

2017-07-10 20:18 UTC, rafaels88 approved these changes

2017-07-11 19:47 UTC, DavidBarDo commented on microfonia/templates/home.html
> +		<a href="#" class="more-link button-font aligncenter">LEIA MAIS <i class="fa fa-long-arrow-right" aria-hidden="true"></i></i></a>
Esse botão está ficando azul e sublinhado depois de visitado, tem que mudar o style lá no css pra ele não mudar depois de clicado.

2017-07-11 19:50 UTC, DavidBarDo commented on microfonia/templates/base.html
> +		<button class="menu-button button-font"><i id='menu-open' class="fa fa-bars" aria-hidden="true"></i><i id='menu-close' class="fa fa-times hide" aria-hidden="true"></i>MENU</button>
Que é essa tag <i>

2017-07-11 19:54 UTC, DavidBarDo commented on microfonia/static/microfonia/template-mobile.css
> +@media only screen and (max-width: 1024px) {
Na verdade eu to comentando aqui pq não consegui comentar acima, mas que que vc fez nesse jquery?

2017-07-11 19:56 UTC, DavidBarDo commented on microfonia/templates/base.html
> +<script src="{% static 'microfonia/jquery/jquery-3.2.1.min.js' %}"></script>
Aqui ele de novo, o Jquery

2017-07-11 20:02 UTC, davelopeer reviewed
Fiz alguns comentários, mas só um que é pra mudar algo mesmo, o resto é dúvida

2017-07-12 00:45 UTC, davibortolotti commented on microfonia/templates/home.html
> +		<a href="#" class="more-link button-font aligncenter">LEIA MAIS <i class="fa fa-long-arrow-right" aria-hidden="true"></i></i></a>
vou mudar!

2017-07-12 00:47 UTC, davibortolotti commented on microfonia/templates/base.html
> +		<button class="menu-button button-font"><i id='menu-open' class="fa fa-bars" aria-hidden="true"></i><i id='menu-close' class="fa fa-times hide" aria-hidden="true"></i>MENU</button>
na verdade não precisava ser tag I, podia ser qualquer tag de texto. A tag I é pra voce definir um outro estilo de texto dentro de uma frase, tipo uma palavra em itálico, ou um sublinhado. Como geralmente eu uso esse 'font-awesome' que é uma fonte pra esses simboloszinhos que usa-se bastante na internet, ele muitas vezes vem junto de outro texto com outra formatação, aí por isso boto na I. Nesse caso não fez diferença.

2017-07-12 00:48 UTC, davibortolotti commented on microfonia/static/microfonia/template-mobile.css
> +@media only screen and (max-width: 1024px) {
Não entendi. O que eu fiz em que jquery?

2017-07-12 00:48 UTC, davibortolotti commented on microfonia/templates/base.html
> +<script src="{% static 'microfonia/jquery/jquery-3.2.1.min.js' %}"></script>
aqui tá importando o jquery pra poder utilizar ele lá embaixo, nos scripts.

2017-07-12 11:19 UTC, davibortolotti commented on microfonia/templates/home.html
> +		<a href="#" class="more-link button-font aligncenter">LEIA MAIS <i class="fa fa-long-arrow-right" aria-hidden="true"></i></i></a>
feito!

2017-07-12 11:23 UTC, davibortolotti commented on microfonia/static/microfonia/template-mobile.css
> +@media only screen and (max-width: 1024px) {
Acho que entendi. Eu usei o Jquery pra poder animar o botão do menu. Quando você clica no botão, ele adiciona classes a vários divs diferentes, por exemplo, pro site pular pra esquerda quando o menu fizer 'slide' pra esquerda; pro botão mudar o símbolo dos três pauzinhos pra um 'x'; etc etc etc.

2017-07-12 11:28 UTC, merged

2017-07-12 13:01 UTC, DavidBarDo commented on microfonia/templates/base.html
> +		<button class="menu-button button-font"><i id='menu-open' class="fa fa-bars" aria-hidden="true"></i><i id='menu-close' class="fa fa-times hide" aria-hidden="true"></i>MENU</button>
hm.. eu conhecia como a tag SPAN, é a mesma coisa, a I e a SPAN?

2017-07-12 13:01 UTC, DavidBarDo commented on microfonia/static/microfonia/template-mobile.css
> +@media only screen and (max-width: 1024px) {
entendi!

2017-07-12 13:02 UTC, DavidBarDo commented on microfonia/templates/base.html
> +<script src="{% static 'microfonia/jquery/jquery-3.2.1.min.js' %}"></script>
Entendi